"""AI 模型配置管理（挂 catalog 库）。

表结构参考 Aix-DB 的 t_ai_model：记录供应方 / 模型类型 / base_model /
api_key / api_domain 等信息，运行时由 compiler._init_model 通过
resolve_runtime_model() 查表注入，替代写死的环境变量。
"""
import json
import os
import time

from .. import db as dblayer
from .db import _conn  # noqa: F401  复用 catalog 连接

# 自增主键方言差异：SQLite AUTOINCREMENT / PG IDENTITY
_ID = ("INTEGER PRIMARY KEY AUTOINCREMENT" if not dblayer.is_pg()
       else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")

SUPPLIER_NAMES = {
    1: "OpenAI", 2: "Azure OpenAI", 3: "Ollama", 4: "vLLM",
    5: "DeepSeek", 6: "Qwen", 7: "Moonshot", 8: "ZhipuAI",
    9: "Other", 10: "MiniMax",
}


def init_tables(con=None):
    """幂等建表；catalog.init() 传入已建好基础表的连接复用。"""
    own = con is None
    if own:
        con = _conn()
    con.executescript(f"""
    CREATE TABLE IF NOT EXISTS ai_models(
      id {_ID},
      name TEXT NOT NULL,
      supplier INTEGER NOT NULL,
      model_type INTEGER NOT NULL,
      base_model TEXT NOT NULL,
      default_model INTEGER DEFAULT 0,
      api_key TEXT,
      api_domain TEXT NOT NULL,
      protocol INTEGER DEFAULT 1,
      config TEXT,
      status INTEGER DEFAULT 1,
      created_at TEXT);
    CREATE INDEX IF NOT EXISTS idx_ai_models_default ON ai_models(default_model);
    CREATE INDEX IF NOT EXISTS idx_ai_models_base ON ai_models(base_model);
    """)
    con.commit()
    if own:
        con.close()


# ---------------------------------------------------------------------------
# CRUD
# ---------------------------------------------------------------------------

def _row(r):
    if r is None:
        return None
    d = dict(r)
    if d.get("config"):
        try:
            d["config_list"] = json.loads(d["config"])
        except Exception:
            d["config_list"] = []
    else:
        d["config_list"] = []
    return d


def list_models(keyword="", model_type=None):
    """列表查询，支持按名称/base_model 关键词和模型类型筛选。"""
    where, params = [], []
    if keyword:
        where.append("(name LIKE ? OR base_model LIKE ?)")
        params += [f"%{keyword}%", f"%{keyword}%"]
    if model_type:
        where.append("model_type=?")
        params.append(model_type)
    cond = (" WHERE " + " AND ".join(where)) if where else ""
    con = _conn()
    rows = con.execute(
        f"SELECT * FROM ai_models{cond} ORDER BY default_model DESC, id DESC",
        params).fetchall()
    con.close()
    return [_row(r) for r in rows]


def get_model(model_id):
    con = _conn()
    r = con.execute("SELECT * FROM ai_models WHERE id=?", (model_id,)).fetchone()
    con.close()
    return _row(r)


def create_model(data):
    con = _conn()
    mid = dblayer.insert_returning_id(
        con,
        "INSERT INTO ai_models(name, supplier, model_type, base_model, "
        "default_model, api_key, api_domain, protocol, config, status, created_at) "
        "VALUES(?,?,?,?,?,?,?,?,?,?,?)",
        (data["name"], data.get("supplier", 1), data.get("model_type", 1),
         data["base_model"], 0, data.get("api_key", ""),
         data["api_domain"], data.get("protocol", 1),
         _encode_config(data.get("config_list")), 1,
         time.strftime("%Y-%m-%d %H:%M:%S")))
    con.commit()
    con.close()
    return mid


def update_model(model_id, data):
    before = get_model(model_id)
    if not before:
        return False
    con = _conn()
    con.execute(
        "UPDATE ai_models SET name=?, supplier=?, model_type=?, base_model=?, "
        "api_key=?, api_domain=?, protocol=?, config=? WHERE id=?",
        (data.get("name", before["name"]),
         data.get("supplier", before["supplier"]),
         data.get("model_type", before["model_type"]),
         data.get("base_model", before["base_model"]),
         data.get("api_key", before["api_key"]),
         data.get("api_domain", before["api_domain"]),
         data.get("protocol", before["protocol"]),
         _encode_config(data.get("config_list")),
         model_id))
    con.commit()
    con.close()
    return True


def delete_model(model_id):
    con = _conn()
    cur = con.execute("DELETE FROM ai_models WHERE id=?", (model_id,))
    con.commit()
    con.close()
    return cur.rowcount > 0


def set_default_model(model_id):
    """设为默认：先清所有 default_model=0，再置目标为 1。"""
    con = _conn()
    row = con.execute("SELECT 1 FROM ai_models WHERE id=?", (model_id,)).fetchone()
    if not row:
        con.close()
        return False
    con.execute("UPDATE ai_models SET default_model=0")
    con.execute("UPDATE ai_models SET default_model=1 WHERE id=?", (model_id,))
    con.commit()
    con.close()
    return True


def get_default_model():
    con = _conn()
    r = con.execute(
        "SELECT * FROM ai_models WHERE default_model=1 AND status=1 LIMIT 1"
    ).fetchone()
    con.close()
    return _row(r)


# ---------------------------------------------------------------------------
# 运行时解析 + 种子
# ---------------------------------------------------------------------------

def resolve_runtime_model(model_str):
    """供 compiler._init_model 调用：按 model_str 查 DB 取 api_key/api_domain。

    解析顺序：
    1. strip "openai:" 前缀 → 得到 base_model 名 → 查 DB 精确匹配
    2. 未命中 → 查 DB 默认模型（default_model=1）
    3. 都没有 → 返回 None（回退到环境变量）

    返回 dict: {base_model, api_key, api_domain, protocol} 或 None。
    """
    if not model_str:
        # 没指定模型名，直接看默认
        d = get_default_model()
        return _runtime_cfg(d) if d else None
    base = model_str.split(":", 1)[1] if ":" in model_str else model_str
    con = _conn()
    r = con.execute(
        "SELECT * FROM ai_models WHERE base_model=? AND status=1 LIMIT 1",
        (base,)).fetchone()
    con.close()
    if r:
        return _runtime_cfg(_row(r))
    # 精确未命中 → 默认模型
    d = get_default_model()
    return _runtime_cfg(d) if d else None


def _runtime_cfg(row):
    if not row:
        return None
    return {
        "base_model": row["base_model"],
        "api_key": row.get("api_key") or "",
        "api_domain": row["api_domain"],
        "protocol": row.get("protocol", 1),
    }


def _encode_config(config_list):
    if not config_list:
        return None
    if isinstance(config_list, str):
        return config_list
    try:
        return json.dumps(config_list, ensure_ascii=False)
    except Exception:
        return None


def seed_default_model_if_empty():
    """表空时从环境变量播种一条默认模型记录（幂等）。"""
    con = _conn()
    cnt = con.execute("SELECT COUNT(*) AS c FROM ai_models").fetchone()["c"]
    if cnt > 0:
        con.close()
        return
    model_name = os.environ.get("MODEL_NAME", "")
    if not model_name:
        con.close()
        return
    base = model_name.split(":", 1)[1] if ":" in model_name else model_name
    api_domain = os.environ.get("OPENAI_BASE_URL", "")
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_domain:
        con.close()
        return
    dblayer.insert_returning_id(
        con,
        "INSERT INTO ai_models(name, supplier, model_type, base_model, "
        "default_model, api_key, api_domain, protocol, config, status, created_at) "
        "VALUES(?,?,?,?,?,?,?,?,?,?,?)",
        ("默认模型", 1, 1, base, 1, api_key, api_domain, 1, None, 1,
         time.strftime("%Y-%m-%d %H:%M:%S")))
    con.commit()
    con.close()
