"""audit 包的库连接与建表（挂 catalog 库，随 catalog.init() 幂等建表）。"""
from .. import db as dblayer
from ..catalog.db import _conn  # noqa: F401  复用 catalog 连接

# 自增主键方言差异：SQLite AUTOINCREMENT / PG IDENTITY
_ID = ("INTEGER PRIMARY KEY AUTOINCREMENT" if not dblayer.is_pg()
       else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")


def init_tables(con=None):
    """幂等建表；catalog.init() 传入已建好基础表的连接复用。"""
    own = con is None
    if own:
        con = _conn()
    con.executescript(f"""
    CREATE TABLE IF NOT EXISTS audit_logs(
      id {_ID},
      actor_id TEXT, actor_name TEXT,
      action TEXT, obj_type TEXT, obj_id TEXT,
      before TEXT, after TEXT,
      ip TEXT, created_at TEXT);
    CREATE INDEX IF NOT EXISTS idx_audit_logs_obj ON audit_logs(obj_type);
    CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs(actor_id);
    CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);
    """)
    con.commit()
    if own:
        con.close()
