"""统一数据库访问层：同一套模块代码同时跑在 SQLite（本地/测试）与 PostgreSQL（共享部署）。

设计：
- DB_BACKEND=sqlite（默认）时，connect(name) 返回真正的 sqlite3.Connection，
  行为与历史版本完全一致，零风险。
- DB_BACKEND=postgres 时，connect(name) 返回 psycopg3 连接的轻包装
  （_PgConn），在 execute/cursor 层做方言翻译：
    * `?` 占位符           -> `%s`
    * `INSERT OR IGNORE`   -> `INSERT ... ON CONFLICT DO NOTHING`
    * `INTEGER PRIMARY KEY AUTOINCREMENT` -> `BIGINT GENERATED BY DEFAULT AS IDENTITY`
    * executescript        -> 按 `;` 拆分逐条执行（建表脚本内无嵌入式分号）
  行对象用 namedtuple_row（同时支持 r[0] 下标与 r["col"] 键访问，对齐 sqlite3.Row）。

- 连接池：psycopg_pool.ConnectionPool，按业务库名（catalog/conversations/...）
  各一个池，懒创建、进程级复用；close() 即归还池。
- 数据库映射：SQLite 一个库一个文件；PostgreSQL 一个库一个 database，
  命名一一对应（catalog.db -> catalog）。

PG 独有注意点：
- cur.lastrowid 不存在，取自增 id 用 insert_returning_id()（内部用 RETURNING）。
- PRAGMA table_info / sqlite_master 不可用，用 table_columns() / table_exists()。
"""

from __future__ import annotations

import logging
import os
import sqlite3
from contextlib import contextmanager

from app.paths import db_path

logger = logging.getLogger("app.db")

# 业务库名清单（与 paths.DB_FILES 对齐；PostgreSQL 下同名 database）
DB_NAMES = ("catalog", "conversations", "checkpoints", "store",
            "traces", "approvals", "ontology")

def _backend() -> str:
    """当前后端（惰性读取：.env 在 FastAPI lifespan 里才加载，import 期不能定值）。"""
    v = os.environ.get("DB_BACKEND", "sqlite").strip().lower()
    if v not in ("sqlite", "postgres"):
        raise RuntimeError(f"不支持的 DB_BACKEND={v!r}，可选 sqlite/postgres")
    return v


def is_pg() -> bool:
    return _backend() == "postgres"


def pg_dsn(db_name: str) -> str:
    """业务库名 -> PostgreSQL DSN（db_name 传 catalog/conversations/... 或带 .db 后缀）。"""
    name = db_name.removesuffix(".db")
    dbname = f"{os.environ.get('POSTGRES_DB_PREFIX', '')}{name}"
    from urllib.parse import quote_plus
    host = os.environ.get("POSTGRES_HOST", "127.0.0.1")
    port = os.environ.get("POSTGRES_PORT", "5432")
    user = os.environ.get("POSTGRES_USER", "uniemployee")
    password = os.environ.get("POSTGRES_PASSWORD", "")
    return (f"postgresql://{user}:{quote_plus(password)}"
            f"@{host}:{port}/{dbname}")


# ---------------------------------------------------------------------------
# PostgreSQL 路径：连接池 + 方言翻译
# ---------------------------------------------------------------------------

class _HybridRow(dict):
    """对齐 sqlite3.Row 的访问方式：r["col"]（键）与 r[0]（下标）都可用，
    dict(r) / r.get() 也照常（业务代码两种访问混用，不能只挑一种）。"""

    __slots__ = ("_values",)

    def __init__(self, mapping, values):
        super().__init__(mapping)
        self._values = values

    def __getitem__(self, key):
        if isinstance(key, (int, slice)):
            return self._values[key]
        return super().__getitem__(key)


def _hybrid_row_factory(cursor):
    if cursor.description is None:
        # 非 SELECT 语句（SET/BEGIN/无 RETURNING 的 INSERT 等）没有列描述
        return lambda values: values
    names = [c.name for c in cursor.description]

    def make_row(values):
        return _HybridRow(zip(names, values), tuple(values))

    return make_row


_pools: dict[str, "object"] = {}


def _get_pool(db_name: str):
    name = db_name.removesuffix(".db")
    pool = _pools.get(name)
    if pool is None:
        from psycopg_pool import ConnectionPool
        pool = ConnectionPool(
            conninfo=pg_dsn(name),
            min_size=1, max_size=8,
            name=f"pool-{name}", open=True,
            kwargs={"row_factory": _hybrid_row_factory},
        )
        _pools[name] = pool
        logger.info("PostgreSQL 连接池就绪: %s", name)
    return pool


def _translate_sql(sql: str, has_params: bool = False) -> str:
    """SQLite 风格 SQL -> PostgreSQL 方言（只做机械翻译，不改语义）。

    has_params=True 时把字面量 ``%`` 转义成 ``%%``（psycopg 客户端参数绑定下
    裸 ``%`` 是保留字符，如 ``LIKE 'c_%'``）；无参数时 psycopg 不做占位符
    解析，不能转义。
    """
    s = sql.strip()
    # INSERT OR IGNORE -> ON CONFLICT DO NOTHING（这些语句都是简单 VALUES，无尾缀子句）
    if "INSERT OR IGNORE INTO" in s:
        s = s.replace("INSERT OR IGNORE INTO", "INSERT INTO")
        if "ON CONFLICT" not in s:
            s = s.rstrip(";").rstrip() + " ON CONFLICT DO NOTHING"
    # 自增主键（建表语句）
    s = s.replace("INTEGER PRIMARY KEY AUTOINCREMENT",
                  "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    # 字面量 % 转义（必须在 ? -> %s 之前做）
    if has_params:
        s = s.replace("%", "%%")
    # 占位符
    s = s.replace("?", "%s")
    return s


# 已执行过的建表脚本缓存（按 池名+脚本内容 去重，避免每次连接都跑 DDL）
_scripts_done: set[tuple[str, int]] = set()


class _PgCursor:
    """psycopg 游标包装：execute 前做方言翻译。"""

    def __init__(self, cur):
        self._cur = cur

    def execute(self, sql, params=()):
        p = params if params else None
        return self._cur.execute(_translate_sql(sql, p is not None), p)

    def __getattr__(self, item):
        return getattr(self._cur, item)

    def __iter__(self):
        return iter(self._cur)


class _PgConn:
    """psycopg 连接包装：
    - execute/cursor 做方言翻译；
    - close() = 提交并归还连接池（对齐模块里 con.commit(); con.close() 的用法）；
    - 支持 `with con:`（提交/回滚后归还）；
    - 被 GC 回收时也自动归还（对齐 sqlite 连接靠 GC 兜底关闭的旧语义，
      防止漏 close 的代码路径耗尽连接池）。
    """

    def __init__(self, raw, db_name: str, release):
        self._raw = raw
        self._db = db_name.removesuffix(".db")
        self._release = release
        self._released = False

    def _do_release(self):
        if self._released:
            return
        self._released = True
        try:
            self._release()
        except Exception:
            logger.warning("归还 PostgreSQL 连接失败（pool-%s）", self._db, exc_info=True)

    # --- SQL 执行 ---
    def execute(self, sql, params=()):
        p = params if params else None
        cur = self._raw.execute(_translate_sql(sql, p is not None), p)
        return _PgCursor(cur) if cur is not None else None

    def cursor(self, *a, **kw):
        return _PgCursor(self._raw.cursor(*a, **kw))

    def executescript(self, script: str):
        """SQLite executescript 等价：拆分多语句执行（脚本内不能有分号字面量）。"""
        key = (self._db, hash(script))
        skip = key in _scripts_done
        stmts = [s.strip() for s in script.split(";") if s.strip()]
        with self._raw.transaction():
            for st in stmts:
                if skip:
                    # 已建过表：只跑幂等 DDL 也没意义，跳过整段
                    continue
                self._raw.execute(_translate_sql(st))
        if not skip:
            _scripts_done.add(key)

    # --- 事务 / 生命周期 ---
    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        try:
            self.commit()
        except Exception:
            logger.warning("close 前提交失败（pool-%s），回滚后归还", self._db, exc_info=True)
            try:
                self.rollback()
            except Exception:
                pass
        self._do_release()

    def __del__(self):
        # GC 兜底归还（对齐 sqlite 连接靠 GC 关闭的旧语义，防止漏 close 耗尽池）
        self._do_release()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type is None:
                self.commit()
            else:
                self.rollback()
        finally:
            self._do_release()
        return False

    def __getattr__(self, item):
        return getattr(self._raw, item)


def close_all_pools():
    """进程退出时清理（FastAPI lifespan 结束时调用）。"""
    for name, pool in list(_pools.items()):
        try:
            pool.close()
        except Exception:
            logger.warning("关闭 PostgreSQL 连接池 %s 失败", name, exc_info=True)
    _pools.clear()


# ---------------------------------------------------------------------------
# 统一入口
# ---------------------------------------------------------------------------

def connect(db_name: str):
    """按后端返回连接：sqlite -> sqlite3.Connection；postgres -> _PgConn。

    db_name 传业务库名（catalog / conversations / ...），sqlite 下自动映射到
    paths.db_path(db_name + '.db')。
    """
    if is_pg():
        pool = _get_pool(db_name)
        raw = pool.getconn()
        raw.autocommit = False

        def _release(_raw=raw, _pool=pool):
            _pool.putconn(_raw)

        return _PgConn(raw, db_name, _release)
    name = db_name if db_name.endswith(".db") else f"{db_name}.db"
    con = sqlite3.connect(str(db_path(name)))
    con.row_factory = sqlite3.Row
    return con


# ---------------------------------------------------------------------------
# 可移植的 schema 内省与自增 id（替代 PRAGMA / sqlite_master / lastrowid）
# ---------------------------------------------------------------------------

def table_columns(con, table: str) -> list[str]:
    """返回表的列名清单（sqlite: PRAGMA；postgres: information_schema）。"""
    if isinstance(con, _PgConn):
        rows = con.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = ? ORDER BY ordinal_position", (table,)).fetchall()
        return [r[0] for r in rows]
    return [r[1] for r in con.execute(f"PRAGMA table_info({table})")]


def table_exists(con, table: str) -> bool:
    if isinstance(con, _PgConn):
        row = con.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = ?",
            (table,)).fetchone()
        return row is not None
    row = con.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone()
    return row is not None


def insert_returning_id(con, sql: str, params=()) -> int | None:
    """INSERT 并返回自增主键 id（sqlite: lastrowid；postgres: RETURNING id）。

    sql 必须是不带尾缀子句的简单 INSERT，PostgreSQL 下自动追加 RETURNING id。
    """
    if isinstance(con, _PgConn):
        cur = con.execute(sql.rstrip().rstrip(";") + " RETURNING id", params)
        row = cur.fetchone()
        return row[0] if row else None
    cur = con.cursor()
    cur.execute(sql, params)
    return cur.lastrowid


def ping(db_name: str) -> None:
    """连通性探测（health 检查用）。失败抛异常。"""
    con = connect(db_name)
    try:
        con.execute("SELECT 1")
        con.commit()
    finally:
        con.close()
