"""guard 包的库连接与建表（挂 catalog 库，随 catalog.init() 幂等建表）。"""
from .. import db as dblayer
from ..catalog.db import _conn  # noqa: F401  复用 catalog 连接

# 自增主键方言差异：SQLite AUTOINCREMENT / PG IDENTITY
_ID = ("INTEGER PRIMARY KEY AUTOINCREMENT" if not dblayer.is_pg()
       else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")


def init_tables(con=None):
    """幂等建表；catalog.init() 传入已建好基础表的连接复用。"""
    own = con is None
    if own:
        con = _conn()
    con.executescript(f"""
    CREATE TABLE IF NOT EXISTS guard_settings(
      key TEXT PRIMARY KEY, value TEXT, updated_at TEXT);
    CREATE TABLE IF NOT EXISTS sensitive_words(
      id {_ID}, word TEXT UNIQUE, category TEXT,
      level TEXT, created_at TEXT, deleted_at TEXT);
    CREATE INDEX IF NOT EXISTS idx_sensitive_words_word ON sensitive_words(word);
    CREATE TABLE IF NOT EXISTS guard_logs(
      id {_ID}, event_type TEXT, detail TEXT,
      user_id TEXT, employee_id TEXT, conversation_id TEXT,
      extra TEXT, created_at TEXT);
    CREATE INDEX IF NOT EXISTS idx_guard_logs_type ON guard_logs(event_type);
    """)
    con.commit()
    if own:
        con.close()
